### ISSUE TITLE
connect.Ping() results in bad connection error

### ISSUE THREAD

**Issue by rodrigo-garcia-edo** [nikepan/clickhouse-bulk#13]
One common practice after creating the connection is to check for Ping/Pong from server

```
if err := connect.Ping(); err != nil {
	logger.Fatal(err)
	return nil, err
}
```

This method works as intended when connecting to a clickhouse server via either http or tcp.

When i connect instead to clickhouse-bulk http i receive bad connection error from the driver.

**Comment by nikepan** [comment]
I think, you use https://github.com/kshvakov/clickhouse/, it use TCP protocol.
clickhouse-bulk uses only simple HTTP requests (
