### ISSUE TITLE
Credential disclosure in logs

### ISSUE THREAD

**Issue by joe-bowman** [nikepan/clickhouse-bulk#17]
If forwarding queries on to a server requiring authentication, if URL is of the form http://username:password@localhost:8123, these credentials are disclosed in the log file by https://github.com/nikepan/clickhouse-bulk/blob/4f084dd00b9c39e21a32cffedfc54d314bb46f18/clickhouse.go#L182

We should redact the password portion of this string before echoing it.

**Comment by nikepan** [comment]
oh. thanks. I'll fix it tomorrow

**Comment by nikepan** [comment]
fixed https://github.com/nikepan/clickhouse-bulk/releases/tag/v1.2.2 - log only server url
