### ISSUE TITLE
No working clickhouse servers

### ISSUE THREAD

**Issue by ckjet** [nikepan/clickhouse-bulk#22]
{
  "listen": ":8124",
  "flush_count": 10000,
  "flush_interval": 1000,
  "dump_check_interval": 300,
  "debug": false,
  "dump_dir": "dumps",
  "clickhouse": {
    "down_timeout": 60,
    "connect_timeout": 10,
    "servers": [
      "http://clickhouse:clickhouse@127.0.0.1:8123"
    ]
  }
}

`$ curl -s http://127.0.0.1:8124/metrics | grep "^ch_"
ch_bad_servers 0
ch_dump_count 0
ch_good_servers 0
ch_queued_dumps 0
ch_received_count 0
ch_sent_count 0
`

`$curl http://clickhouse:clickhouse@127.0.0.1:8123 
Ok.
`

It seems that he does not see servers, how can I solve this problem?

**Comment by nikepan** [comment]
может учетные данные в конфиге не проходят. их надо передавать с клиентов. тут просто сервера

**Comment by ckjet** [comment]
А можно пример как это сделать?

**Comment by nikepan** [comment]
пример конфига в ридми)
а на клиенте зпависит от языка. если на питоне, то что-то типа вот этого
https://requests.readthedocs.io/en/master/user/authentication/
но можно и просто user и password в get параметрах передавать

**Comment by ckjet** [comment]
Клиент сдандартный идет с документации clickhouse:

FROM yandex/clickhouse-client:19.15 as build

**Comment by nikepan** [comment]
эта утилита не предназначена для стандартного клиента, хотя наверное должна работать. по идее надо просто в ней прописать логин и пароль при подключении. сначала попробуйте подключиться к оригинальному серверу, а затем с теми же настройками через clickhouse-bulk, указав у него в конфиге просто адрес сервера

**Comment by nikepan** [comment]
а, нет. прошу прощения. она же работает через свой протокол. а утилита принимает только http запросы. возможно вы пытаетесь сделать что-то не то, для чего она предназначена. попробуйте сначала настроить все без нее. а потом уже поставить ее посередине.

**Comment by ckjet** [comment]
Я пробовал управлять через devOps - все таблицы и данные отображаются. С теми же настройками пытаюсь настроить clickhouse-bulk

**Comment by nikepan** [comment]
а через какую библиотеку вы отправляете данные в кликхаус сейчас?

**Comment by ckjet** [comment]
https://github.com/esazykin/laravel-clickhouse

**Comment by nikepan** [comment]
По идее только вот тут в конфиге пароль нужно задавать. в clickhouse-bulk просто сервер указать. а в этом конфиге ссылку на него
```
'connections' => [
    'clickhouse' => [
        'driver' => 'clickhouse',
        'cluster' => [
            'server-1' => [
                'host' => '',
                'port' => '',
                'database' => '',
                'username' => '',
                'password' => '',
                'options' => [
                    'timeout' => 10,
                    'protocol' => 'https'
                ]
            ],
            'server-2' => [
                'host' => '',
                'port' => '',
                'database' => '',
                'username' => '',
                'password' => '',
                'options' => [
                    'timeout' => 10,
                    'protocol' => 'https'
                ]
            ]
        ]
    ]
]
```

**Comment by ckjet** [comment]
Так это в указанной мной библиотеке? Я не совсем понимаю как это поможет увидеть сервер через clickhouse-bulk.

**Comment by nikepan** [comment]
через clickhouse-bulk не нужно видеть сервер) он наоборот собирает запросы и сам их туда отправляет, но использует учетные данные из запросов, пришедших на него.
поэтому в нем нужно просто указать адрес сервера clickhouse
"servers": [
"http://127.0.0.1:8123"
]

**Comment by ckjet** [comment]
Если указать таким образом, то все также в статистике серверов нет:

`$ curl -s http://127.0.0.1:8124/metrics | grep "^ch_"
ch_bad_servers 0
ch_dump_count 0
ch_good_servers 0
ch_queued_dumps 0
ch_received_count 0
ch_sent_count 0
`

**Comment by nikepan** [comment]
статистика копится только когда есть запросы. пока запросов нет, там все по нулям по идее будет

**Comment by ckjet** [comment]
Я думал не видит серверов. Действительно при добавлениях появилась статистка. Спасибо большое за помощь!
