### ISSUE TITLE
How to guarantee data reliability?

### ISSUE THREAD

**Issue by unidbaas** [nikepan/clickhouse-bulk#30]
The data will multi in memory, and if the service dead when the data is saved too much, the data will be lost

**Comment by nikepan** [comment]
You can set a short dispatch period. There are currently no ways to increase reliability.

**Comment by unidbaas** [comment]
> You can set a short dispatch period. There are currently no ways to increase reliability.

I also implemented a packer myself, which has the same function as yours, but today the leader suddenly asked me, how to guarantee the reliability of data...............

**Comment by nikepan** [comment]
All tools are made for their tasks. Those who need reliability can afford to write for their tasks. This utility is needed more for collecting site statistics on python and php and can afford to lose a second of data.

**Comment by unidbaas** [comment]
> All tools are made for their tasks. Those who need reliability can afford to write for their tasks. This utility is needed more for collecting site statistics on python and php and can afford to lose a second of data.

Yes, I think we have to find a way to minimize the damage
