### ISSUE TITLE
http interface

### ISSUE THREAD

**Issue by alifpay** [nikepan/clickhouse-bulk#34]
Hi

Why do you HTTP interface for Clickhouse?
Is it better than [clickhouse-go](https://github.com/ClickHouse/clickhouse-go) ?

**Comment by nikepan** [comment]
No, but it makes very simple to join small http queries from python/php projects

**Comment by nikepan** [comment]
And clickhouse-go - is a library, and clikchouse-bulk is a tool

**Comment by alifpay** [comment]
No, I mean in your project, you are using  HTTP interface (Golang HTTP client) to connect with Clickhouse. 
Why you do not use Clickhouse driver like clickhouse-go?

**Comment by dink10** [comment]
@alifpay I guess you can fork and provide alternative solution covered tests with clickhouse-go instead on HTTP Golang client. If you would like I can help you in that idea :)

**Comment by alifpay** [comment]
Just interesting, I found another project [kittenhouse](https://github.com/VKCOM/kittenhouse) that uses HTTP interface

**Comment by nikepan** [comment]
I have no time for grow this app. And I think, it is not very actual, because this service for small projects. Big projects can write own collectors for their highload. But you can write alternate sender class. And we connect it with config option.

**Comment by alifpay** [comment]
clickhouse-go
does not support batch insert, like bellow 
```
conn.Exec(`INSERT INTO table3 (c1, c2, c3) VALUES ('v1', 'v2', 'v3')('v4', 'v5', 'v6')`)
```
thank you very much.
