### ISSUE TITLE
ERROR: Send (503) No working clickhouse servers; response

### ISSUE THREAD

**Issue by khlystov** [nikepan/clickhouse-bulk#39]
Периодически под нагрузкой падает такой лог

clickhouse-bulk_1  | 2021/03/05 11:03:10.847398 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.847752 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.847858 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.847954 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848023 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848081 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848224 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848425 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848488 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848615 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848839 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.848950 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.849238 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.849771 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.850151 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.850361 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.850426 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.850513 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.850565 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:03:10.850753 ERROR: Send (503) No working clickhouse servers; response
clickhouse-bulk_1  | 2021/03/05 11:04:32.243796 INFO: sending 26 rows to http://default:root@11111111:8123 of INSERT INTO lkdn_profiles.employees (
clickhouse-bulk_1  | 2021/03/05 11:04:42.244128 ERROR: server down (502): Post http://default:***@11111111:8123: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
clickhouse-bulk_1  | 2021/03/05 11:04:42.244156 INFO: sending 26 rows to http://default:root@11111111:8123 of INSERT INTO lkdn_profiles.employees (
clickhouse-bulk_1  | 2021/03/05 11:04:52.244517 ERROR: server down (502): Post http://default:***@11111111:8123: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
clickhouse-bulk_1  | 2021/03/05 11:04:52.244552 INFO: sending 26 rows to http://default:root@11111111:8123 of INSERT INTO lkdn_profiles.employees (
clickhouse-bulk_1  | 2021/03/05 11:05:02.244919 ERROR: server down (502): Post http://default:***@11111111:8123: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
clickhouse-bulk_1  | 2021/03/05 11:05:02.244950 INFO: sending 26 rows to http://default:root@11111111:8123 of INSERT INTO lkdn_profiles.employees (
clickhouse-bulk_1  | 2021/03/05 11:05:12.245236 ERROR: server down (502): Post http://default:***@11111111:8123: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
clickhouse-bulk_1  | 2021/03/05 11:05:12.245261 INFO: sending 26 rows to http://default:root@11111111:8123 of INSERT INTO lkdn_profiles.employees (
clickhouse-bulk_1  | 2021/03/05 11:05:22.245596 ERROR: server down (502): Post http://default:***@11111111:8123: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
clickhouse-bulk_1  | 2021/03/05 11:05:22.245626 ERROR: server error (503) No working clickhouse servers

но при этом сам сервер кх жив
echo 'SELECT 1' | curl 'http://default:root@1111:8123/' --data-binary @-
1

**Comment by nikepan** [comment]
как вариант, можно попробовать увеличить connect_timeout в конфиге. видимо кх очень долго вставляет. так же можно сделать более редкой вставку (интервал или количество записей увеличить в конфиге).
ну и к этим вариантам можно добавить еще реплику кх, чтобы когда один падает, второй начал использоваться. пока первый не оживет
